name: Portfolio Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::598428563938:role/GitHub_Actions_To_S3
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://static-hosted-bucket --delete

